# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.14.x

# Only clone the most recent commit.
git:
  depth: 1

script:
  - make test